### ISSUE TITLE
Update praw syntax to reflect newer versions

### ISSUE THREAD

**Issue by Deadstar106** [EliteDangerous-Subreddit/reddit-twitter-bot#1]
Current implementation of praw only works up to version 3.6.0. Newer versions require a client_id and a client_secret in order to function; this could be taken from an app with u/EliteDangerousBot or elsewhere.
Either that or just install version 3.6.0 instead.

**Comment by Venefilyn** [comment]
If you do this, do it in a feature branch and commit upstream as well

**Comment by Deadstar106** [comment]
Updated version pushed into "update_praw" branch. Should _probably_ work.
