### ISSUE TITLE
Temporary image does not get deleted if error occurs between downloading and removing

### ISSUE THREAD

**Issue by Venefilyn** [EliteDangerous-Subreddit/reddit-twitter-bot#7]
If an exception is had between downloading and removing the image it should restore to original state pre-download. Which from my knowledge would be to only remove the image

**Comment by Deadstar106** [comment]
Added a try/except clause when uploading the tweet w/ image media, which seems right about the only place it can fail between successfully downloading and uploading the image.
Relevant changes in commit 63accfb2991677a8bd3a3f047f92117ba25a6ada
