### ISSUE TITLE
Bug fix: bool configs

### ISSUE THREAD

**Issue by zeshinsei** [EliteDangerous-Subreddit/reddit-twitter-bot#9]
Any bool configs that need to be pulled in should be:

`NSFW_ALLOWED         = bool(settings.getboolean('nsfw_allowed'))`

Currently they are incorrect and never retrieve the bool state correctly;

`NSFW_ALLOWED         = bool(settings.get('nsfw_allowed'))`

**Comment by Deadstar106** [comment]
Thanks for finding this, fixed in 8333ba4dd584cdbe6922f412b6fee0274dedded6
